[School]
from              = Runxi Yu <s22537@ykpaoschool.cn>
default           = INBOX
copy-to           = Sent Items
source            = imaps+xoauth2://s22537%40ykpaoschool.cn@outlook.office365.com
source-cred-cmd   = ~/.local/bin/ykps-mutt_oauth2.py ~/.cache/aerc/token.txt
outgoing          = smtp+xoauth2://s22537%40ykpaoschool.cn@outlook.office365.com:587
outgoing-cred-cmd = ~/.local/bin/ykps-mutt_oauth2.py ~/.cache/aerc/token.txt

[New]
source            = maildir://~/.local/share/mail/runxiyu
check-mail-cmd    = /usr/bin/env mailsync
outgoing          = /usr/bin/env msmtp --account=runxiyu
default           = Inbox
from              = Runxi Yu <me@runxiyu.org>
copy-to           = Sent

[Old]
source            = imaps://andrew%40andrewyu.org@mail.andrewyu.org
source-cred-cmd   = pass show andrewyu.org/andrew
outgoing          = smtps://andrew%40andrewyu.org@mail.andrewyu.org
outgoing-cred-cmd = pass show andrewyu.org/andrew
default           = INBOX
from              = Runxi Yu <andrew@andrewyu.org>
copy-to           = Sent
