[main]
# source            = maildir://~/.local/share/mail/runxiyu
source            = notmuch://~/.local/share/mail/runxiyu
maildir-store     = ~/.local/share/mail/runxiyu
check-mail-cmd    = /usr/bin/env mailsync
outgoing          = /usr/bin/env msmtp --account=runxiyu
default           = Inbox
from              = Runxi Yu <me@runxiyu.org>
copy-to           = Sent

[school]
from              = Runxi Yu <s22537@ykpaoschool.cn>
default           = INBOX
copy-to           = Sent Items
source            = imaps+xoauth2://s22537%40ykpaoschool.cn@outlook.office365.com
source-cred-cmd   = ~/.local/bin/ykpsmuttauth ~/.cache/aerc/token.txt
outgoing          = smtp+xoauth2://s22537%40ykpaoschool.cn@outlook.office365.com:587
outgoing-cred-cmd = ~/.local/bin/ykpsmuttauth ~/.cache/aerc/token.txt

[ld]
source            = imaps://runxiyuld%40runxiyu.org@mail.runxiyu.org
source-cred-cmd   = pass show runxiyu.org/runxiyuld
outgoing          = smtps://runxiyuld%40runxiyu.org@mail.runxiyu.org
outgoing-cred-cmd = pass show runxiyu.org/runxiyuld
default           = INBOX
from              = Runxi Yu <runxiyu-ld@runxiyu.org>
copy-to           = Sent

[old]
source            = imaps://andrew%40andrewyu.org@mail.andrewyu.org
source-cred-cmd   = pass show andrewyu.org/andrew
outgoing          = smtps://andrew%40andrewyu.org@mail.andrewyu.org
outgoing-cred-cmd = pass show andrewyu.org/andrew
default           = INBOX
from              = Runxi Yu <andrew@andrewyu.org>
copy-to           = Sent

[mdirect]
source            = imaps://me%40runxiyu.org@mail.runxiyu.org
source-cred-cmd   = pass show runxiyu.org/me
outgoing          = smtps://me%40runxiyu.org@mail.runxiyu.org
outgoing-cred-cmd = pass show runxiyu.org/me
default           = INBOX
from              = Runxi Yu <me@runxiyu.org>
copy-to           = Sent
