set config.saving_style_w = 1
set terminal.foot.transparency = 1
set terminal.foot.colors = 4
set ui.language = "System"
set ui.colors.color.desktop.text = "white"
set ui.colors.color.desktop.background = "black"
set terminal.tmux-256color.transparency = 1
set terminal.tmux-256color.colors = 4
