#!/bin/sh

hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x70000002A}]}'

# sudo defaults write com.apple.loginwindow LoginHook <path to this script>
